### ISSUE TITLE
`browser` vs `module`

### ISSUE THREAD

**Issue by stereobooster** [stereobooster/package.json#2]
1. `browser` was added as an intention to ship browser specific builds via npm (along with node.js specific builds)
2. `module` was added as intention to ship modern js (ES2015 aka ES6 or later)

```
main --(1)--> browser
 |               |
 |               |
(2)              |
 |               |
 ˅               ˅
module --------> ?

```

As a result, there is obvious hole - how do you deliver modern js for browser specific builds

Suggested solutions:

- [`module-browse`](https://github.com/webpack/webpack/issues/4674)
- [`esm: true`](https://github.com/nodejs/node-eps/pull/60)
- [`esnext`](http://2ality.com/2017/04/transpiling-dependencies-babel.html)

Related:
- [Draft ES Module Interoperability](https://github.com/nodejs/node-eps/blob/master/002-es-modules.md)
- [In Defense of .js](https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md)
- [es-module-loader](https://github.com/ModuleLoader/es-module-loader)
- [reify](https://github.com/benjamn/reify)

**Comment by jskrzypek** [comment]
@defunctzombie has a spec for the `browser` field here: https://github.com/defunctzombie/package-browser-field-spec

This is what webpack is using and references in their docs (here: https://webpack.js.org/configuration/resolve/#resolve-aliasfields)

**Comment by stereobooster** [comment]
@jskrzypek yes I know

**Comment by kevlened** [comment]
The solution by the PouchDB team seems to be based on that spec: https://github.com/rollup/rollup-plugin-node-resolve/issues/8#issuecomment-257323750

I didn't realize the browser field could be a map. Using it that way allows both browser and node ES6 modules in the same library.

This method is supported in rollup, [it appears to be supported in webpack](https://gist.github.com/defunctzombie/4339901#gistcomment-1582456), [they reference a browser map in JSPM](https://github.com/jspm/npm/issues/115), and [it's in the browserify handbook](https://github.com/browserify/browserify-handbook#browser-field).

I think that's enough support to say it's a solution, unless I misunderstand the problem you're trying to solve?

**Comment by stereobooster** [comment]
proposed solution with `browser`

```
"main":   "xyz.js",
"module": "xyz.esm.js",
"browser": {
  "xyz.js":     "xyz.browser.js",
  "xyz.esm.js": "xyz.browser.esm.js"
}
```

If you use `require("xyz")` - you get `xyz.js` e.g. `main`
If you use `import "xyz"` - you get `xyz.esm.js`  e.g. `module`
If you use `require("xyz")` and you target browser - you get what? If your answer `xyz.browser.js`, what bundlers support this?
If you use `import "xyz"` and you target browser - you get what? If your answer `xyz.browser.esm.js`, what bundlers support this?

**Comment by kevlened** [comment]
In rollup and webpack, when targeting the browser and using the following package.json:

`import "xyz"` resolves to `xyz.browser.esm.js`
`require("xyz")` resolves to `xyz.browser.esm.js` by default
you have to disallow "module" field resolution to get `require("xyz")` to be `xyz.browser.js`

```javascript
"main":   "xyz.js",
"module": "xyz.esm.js",
"browser": {
  "./xyz.js":     "./xyz.browser.js",
  "./xyz.esm.js": "./xyz.browser.esm.js"
}
```

Note: Relative paths are required as indicated by [this comment](https://github.com/rollup/rollup-plugin-node-resolve/issues/60#issuecomment-297462611)

I haven't tested in JSPM and browserify, but PouchDB is using this method, so I assume it works

**Comment by stereobooster** [comment]
Webpack always assume browser, but otherwise pretty close. Thanks for the tip. Experiment: https://github.com/stereobooster/main-module-browser-test
